export enum ActionType {
  FECTCH_PRODUCTS = "FECTCH_PRODUCTS",
  FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE",
  ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE",
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  CLEAR_CART = "CLEAR_CART",
  CREATE_ORDER = "CREATE_ORDER",
  CLEAR_ORDER = "CLEAR_ORDER",
  FETCH_ORDERS = "FETCH_ORDERS"
}